# Generated by Django 4.2.4 on 2023-09-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bookingcall_car_loan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcall',
            name='pay_with',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookingcall',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
