# Generated by Django 4.2.4 on 2023-09-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bookingcall_pay_with_bookingcall_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('what_Like_to_Learn', models.CharField(blank=True, help_text='What Would you Like to Learn?', max_length=200, null=True)),
                ('is_nz_permanent', models.BooleanField(default=False, help_text='Are you Aus or NZ Permanent Resident?')),
                ('is_full_time', models.BooleanField(default=False, help_text='Do you work Full Time?')),
                ('is_saving_50k', models.BooleanField(default=False, help_text='Do you have savings of $50k or more?')),
                ('is_capcity_to_save', models.BooleanField(default=False, help_text='Do you have Capacity to Save?')),
                ('do_you_foresee_getting_a_FT_Job_in_next_6_years', models.BooleanField(default=False, help_text='Do you Foresee getting a FT Job in next 6 years?')),
            ],
        ),
    ]
