# Generated by Django 4.2.4 on 2023-09-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_bookingcall_bad_credit_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takequiz',
            name='do_you_foresee_getting_a_FT_Job_in_next_6_years',
        ),
        migrations.RemoveField(
            model_name='takequiz',
            name='email',
        ),
        migrations.RemoveField(
            model_name='takequiz',
            name='is_capcity_to_save',
        ),
        migrations.RemoveField(
            model_name='takequiz',
            name='is_full_time',
        ),
        migrations.RemoveField(
            model_name='takequiz',
            name='is_nz_permanent',
        ),
        migrations.RemoveField(
            model_name='takequiz',
            name='is_saving_50k',
        ),
        migrations.RemoveField(
            model_name='takequiz',
            name='what_Like_to_Learn',
        ),
        migrations.AddField(
            model_name='takequiz',
            name='quiz',
            field=models.TextField(blank=True, help_text='Flow Of Quiz', null=True),
        ),
    ]
