# Generated by Django 4.2.4 on 2023-10-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcall',
            name='meeting_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
