# Generated by Django 4.2.4 on 2023-10-26 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_fulldiscountpromocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulldiscountpromocode',
            name='promo_code',
            field=models.CharField(help_text='The value must be at least 8 characters long.', max_length=20, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='promo_code',
            field=models.CharField(help_text='The value must be at least 8 characters long.', max_length=20, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
