# Generated by Django 4.2.4 on 2023-11-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_fulldiscountpromocode_promo_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullDiscountPromoCode',
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
