# Generated by Django 4.2.4 on 2023-09-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forget_password_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
