# Generated by Django 4.2.4 on 2023-09-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
