# Generated by Django 4.2.4 on 2023-09-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your phone number in international format (e.g., +1234567890).', max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
