# Generated by Django 4.2.4 on 2023-10-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your phone number in international format (e.g., +1234567890).', max_length=50, null=True, verbose_name='Phone Number'),
        ),
    ]
