# Generated by Django 4.2.4 on 2023-10-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hubspot_contact_id',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
