# Generated by Django 4.2.4 on 2023-11-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_hubspot_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_subscription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
