# Generated by Django 4.2.4 on 2023-09-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_usercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='pay_with',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='payment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
