# Generated by Django 4.2.4 on 2023-09-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_usercourse_pay_with_usercourse_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='cousre',
            new_name='course',
        ),
    ]
