# Generated by Django 4.2.4 on 2023-09-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_cousre_usercourse_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.cousre'),
        ),
    ]
