# Generated by Django 4.2.4 on 2023-09-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_preorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preorder',
            options={'ordering': ['-id'], 'verbose_name': 'Pre Order', 'verbose_name_plural': 'Pre Orders'},
        ),
    ]
