# Generated by Django 4.2.4 on 2023-11-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lectures_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='premium_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the Lecture Name.', max_length=200)),
                ('lecture_description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video', models.FileField(help_text='please upload the lecture vide!', upload_to='premium_lectures')),
                ('document', models.FileField(blank=True, help_text='please upload the document related video!', null=True, upload_to='premium_course_documents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'premium_lecture',
                'verbose_name_plural': 'premium_lectures',
                'ordering': ['-id'],
            },
        ),
        migrations.RenameField(
            model_name='lectures',
            old_name='lecure_description',
            new_name='lecture_description',
        ),
    ]
