# Generated by Django 4.2.4 on 2023-11-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_premium_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='user',
        ),
        migrations.DeleteModel(
            name='PreOrder',
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
