# Generated by Django 4.2.4 on 2024-01-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_lectures_video_remove_lectures_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='url_1',
            field=models.URLField(default='https://propstart.s3.amazonaws.com/lectures/PropStart_Trailer.mp4', help_text='please enter the url of the video'),
        ),
        migrations.AlterField(
            model_name='premium_course',
            name='url_1',
            field=models.URLField(default='https://propstart.s3.amazonaws.com/lectures/PropStart_Trailer.mp4', help_text='please enter the url of the video'),
        ),
    ]
